CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    username TEXT NOT NULL,

    password_hash TEXT NOT NULL,

    role TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT users_username_nonblank
        CHECK (char_length(trim(username)) > 0),

    CONSTRAINT users_password_hash_nonblank
        CHECK (char_length(trim(password_hash)) > 0),

    CONSTRAINT users_role_supported
        CHECK (role IN ('user', 'admin')),

    CONSTRAINT users_username_unique
        UNIQUE (username)
);