CREATE TABLE artists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(trim(name)) > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE albums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_id BIGINT NOT NULL
        REFERENCES artists(id)
        ON DELETE RESTRICT,
    title TEXT NOT NULL CHECK (char_length(trim(title)) > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX albums_artist_id_idx
    ON albums(artist_id);

CREATE TABLE tracks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id BIGINT NOT NULL
        REFERENCES albums(id)
        ON DELETE RESTRICT,
    title TEXT NOT NULL CHECK (char_length(trim(title)) > 0),
    duration_ms INTEGER NOT NULL CHECK (duration_ms > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX tracks_album_id_idx
    ON tracks(album_id);